name: RunParaEMT

on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Install python dependencies
      shell: bash -l {0}
      run: |
        pip install pandas oedisi matplotlib numpy helics helics_apps xlrd
    - name: Run paraemt federate
      shell: bash -l {0}
      run: |
        helics_broker -f 1 &
        python test_federate.py
    - name: Archive csvs and pngs
      uses: actions/upload-artifact@v2
      with:
        name: results
        path: |
          *.csv
          *.png